title: Wendell Thomas
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Diego Alejandro Martinez Vergara
tagline: | Magister en tecnologÃ­as de informaciÃ³n| IT Manager| Data engineer ğŸ‘©â€ğŸ’»ğŸ“Š
about-description: # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: dimartinez@fen.uchile.cl # Add your Email address
phone: +569 4894 6754 # Add your Phone number
website: www.drachen.cl # Add your website, do not add http://
linkedin: https://www.linkedin.com/in/dmartinez09/ # Add your Linkedin handle
github: dmartinez09 # Add your Github handle
Resume CV: https://drive.google.com/file/d/1Ggz7IMXrvB1kzD-enMyj2ByojgJySIKu/view?usp=drive_link' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
